--SEPARA EL NAME EN FIRST NAME Y LAST NAME MEDIANTE SUBSTRING
SELECT
	id,
	name,
	SUBSTRING(NAME, 0, POSITION(' ' IN NAME)) as first_name,
	SUBSTRING(NAME, POSITION(' ' IN NAME)+1) as last_name,
	TRIM(SUBSTRING(NAME, POSITION(' ' IN NAME))) as trimmed_last_name
FROM
	USERS;