--ACTUALIZA LOS REGISTROS DE LA TABLA ASIGNANDO LOS VALORES DE first_name y last_name
UPDATE USERS
SET
	FIRST_NAME = SUBSTRING(NAME, 0, POSITION(' ' IN NAME)),
	LAST_NAME = SUBSTRING(NAME, POSITION(' ' IN NAME) + 1);